### ISSUE TITLE
Code background color is not same with background color

### ISSUE THREAD

**Issue by umpirsky** [atom/one-dark-syntax#111] opened 2018-06-24 11:23 UTC
![screenshot from 2018-06-24 13-20-53](https://user-images.githubusercontent.com/208957/41818551-80f650e8-77b1-11e8-9229-54101197de2b.png)

As you can see selection and code background color is lighter then background color on the right.

Using Atom 1.28

**Comment by rsese** [comment] 2018-06-27 00:28
I think this is a duplicate of https://github.com/atom/one-dark-ui/issues/266, see if my comment here helps /cc https://github.com/atom/one-dark-ui/issues/266#issuecomment-400504501.

For future issues, please use the issue template, the information is super helpful for us when triaging issues.

**Closed by rsese** 2018-06-27 00:28 UTC

**Comment by umpirsky** [comment] 2018-06-27 07:50
http://blog.atom.io/2018/06/21/atom-1-28.html#support-for-custom-color-profiles fixed it, thanks. 

However, this looks like BC break. It should select RGB by default and keep same behavior we had before the upgrade.
