### ISSUE TITLE
Comment documentation highlighting is incorrect for class properties.

### ISSUE THREAD

**Issue by RealBlazeIt** [atom/one-dark-syntax#99] opened 2017-08-07 17:39 UTC
Comment documentation highlighting is incorrect. When adding a comment such as:
```js
/**
 * A dog.
 * @prop {string} name The name of the dog.
 */
class Dog { ... }
```
The name of the property would show up as grey like the description, instead of being red. Here is a screenshot of how it looks: http://prntscr.com/g5ip5b This is how the name should look: http://prntscr.com/g5ipc5

I know this can be fixed by putting the comment directly over the property declaration itself, however, both should correctly function, as they do in all other JavaScript syntax highlighters, include GitHub's, as you can see above.

**Comment by ibnesayeed** [comment] 2018-01-02 01:07
In my opinion, tokens of documentation comments should not have the same brightness as the main code body. This makes reading the code very difficult. While syntax highlighting on those token in the comment might be good, but their darkness should be increased to distinguish from the main code body tokens. The following screenshot shows how noisy those comments could look, especially when reading large files. This issue is not specific to just the One Dark theme, but also many other themes. There is [a thread on this matter](https://discuss.atom.io/t/separate-syntax-highlight-rules-for-structured-documentation-comments/51021) in the Discuss portal.

![atom-comment-highlight](https://user-images.githubusercontent.com/65147/34472376-d6d3efea-ef2e-11e7-9c16-ecc4d0d2cc48.png)

**Comment by simurai** [comment] 2018-08-23 06:47
I can't reproduce this issue (anymore). `name` and `CommandOptions` get highlighted.

![screen shot 2018-08-23 at 3 45 08 pm](https://user-images.githubusercontent.com/378023/44509122-af195b00-a6eb-11e8-8c2f-979e1cd5e756.png)

It might got fixed in the language package.

**Closed by simurai** 2018-08-23 06:47 UTC
