### ISSUE TITLE
"const" not colorised in ES6

### ISSUE THREAD

**Issue by Andreyco** [atom/one-dark-syntax#27] opened 2015-05-11 05:26 UTC
"const" keyword is not colorised in destructuring assignment in ES6 .js file
![image](https://cloud.githubusercontent.com/assets/829963/7558969/0a1c7162-f7af-11e4-99c5-facca7f13a47.png)

**Comment by izuzak** [comment] 2015-05-11 09:51
I think this is a duplicate of https://github.com/atom/language-javascript/issues/56.

**Closed by izuzak** 2015-05-11 09:51 UTC
