### ISSUE TITLE
Failed to activate the gruvbox theme

### ISSUE THREAD

**Issue by 7sharp9** [atom/one-dark-syntax#56] opened 2015-12-05 18:03 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [one-dark-syntax](https://github.com/atom/one-dark-syntax) package, v1.1.1

### Stack Trace

Failed to activate the gruvbox theme

```
At variable @mono-3 is undefined in /Applications/Atom.app/Contents/Resources/app.asar/node_modules/one-dark-syntax/styles/language.less:2:9

LessError: variable @mono-3 is undefined
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/one-dark-syntax/styles/language.less:2:9
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "gruvbox",
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Parinfer, v0.9.0
hyperclick, v0.0.35
minimap, v4.16.2
nuclide-file-watcher, v0.0.35
nuclide-fuzzy-filename-provider, v0.0.35
nuclide-open-filenames-provider, v0.0.35
nuclide-quick-open, v0.0.35
nuclide-recent-files-provider, v0.0.35
nuclide-recent-files-service, v0.0.35
proton-mode, v0.1.0
python-yapf, v0.9.1
relative-numbers, v0.2.4
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by lee-dohm** [comment] 2015-12-05 18:12
It looks like the cause for this one is in the config:

```coffee
{
  "core": {
    "themes": [
      "gruvbox",
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

**Comment by simurai** [comment] 2016-06-14 07:22
Closing this. @7sharp9 Feel free to open a new one if you couldn't resolve this.

**Closed by simurai** 2016-06-14 07:22 UTC
Labels: uncaught-exception
