### ISSUE TITLE
What happened to the colours?

### ISSUE THREAD

**Issue by Fequois** [atom/one-dark-syntax#48] opened 2015-09-30 10:03 UTC
The screenshots show beautiful, fizzy colours! They were perhaps a bit too bright for some, but I think over the last few months the One Dark combination has become a little gloomy.

So, since I know about nothing on this subject: is it possible to give the One Dark theme an option to inject a little bright, bold happiness into the syntax? Or do I need to fork this repo and make the changes? 

tl;dr: Can a UI theme control/affect syntax themes in any way?

Apologies if this issue is inappropriate (because it really isn't an issue, more of a question).

**Comment by thomasjo** [comment] 2015-09-30 10:34
This is essentially a duplicate of https://github.com/atom/one-dark-syntax/issues/23. Please see that comment thread for more details. There is a branch (albeit slightly outdated) called `sm-high-contrast` that retains the high contrast seen in the marketing screenshots, so you can clone this repo, checkout that branch and be a (somewhat) happy camper.

I believe there were some suggestion by @simurai in the thread for adding a "high contrast" configuration option to the theme, but not sure what came of that (if I even remember correctly).

Since this is essentially a duplicate and was discussed to death in the aforementioned issue, I'm closing this. If you strongly disagree, feel free to re-open, but we won't bump the contrast (again) outside of introducing an option.

**Closed by thomasjo** 2015-09-30 10:34 UTC

**Comment by simurai** [comment] 2015-09-30 11:33
> adding a "high contrast" configuration option to the theme

Ya, that was my hope, but I haven't found a good way to do it. Some themes override variables on disk, but there are issues with not reloading all the styles.

Maybe I'll just publish the `sm-high-contrast` branch as another theme. Keeping it updated with the core theme shouldn't be too much of a burden.

**Comment by Fequois** [comment] 2015-09-30 11:57
I'm sorry I overlooked that other issue @thomasjo, I didn't read through the entire thing but I agree it's essentially the same thing being discussed.

@simurai That would be cool! `two-dark-syntax`? :laughing:

**Comment by simurai** [comment] 2015-10-01 05:52
@Fequois Ok, it's now its own theme.. `dark-vivid`! https://atom.io/themes/one-dark-vivid-syntax

**Comment by Fequois** [comment] 2015-10-01 13:12
Oh. I like that.

Thanks so much @simurai!
