### ISSUE TITLE
Markdown with mixed HTML can produce incorrect styling

### ISSUE THREAD

**Issue by SmilinBrian** [atom/one-dark-syntax#51] opened 2015-10-17 05:33 UTC
I sometimes use `<a href="blah" target="_blank">` HTML tags in my Markdown code when "open the link in a new browser" behavior is appropriate.

Unfortunately the underscore character with in "_blank" triggers the syntax to try to show "Markdown italicized" formatting until a "closing" underscore is encountered somewhere else.

See attached image.

![onedarkunderscore](https://cloud.githubusercontent.com/assets/139918/10557169/e6ce7772-7455-11e5-9659-ba9325c37049.png)

**Comment by simurai** [comment] 2015-10-17 14:46
This seems to be a duplicate of https://github.com/atom/language-gfm/issues/44.

I'll close this here, but feel free to add a comment there.

**Closed by simurai** 2015-10-17 14:46 UTC

**Comment by SmilinBrian** [comment] 2015-10-17 23:37
Agreed, thanks.
